name: Homework tasks CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to my repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'


    - name: complile all classes
      run: javac -sourcepath Module-303/Module-303/src -d out Module-303/Module-303/src/*.java

    - name: run main class 
      run: java -cp out Main
